### ISSUE TITLE
Refreshing cache gets stuck (Probably due to new PP curve)

### ISSUE THREAD

**Issue by Rocksterdev** [Splamy/ScoreSaberEnhanced#11]
Trying to refresh cache will result in it just getting stuck.

What I also recommend is the ability to update the cache in mass to save on clicks and also to save time.

**Comment by Splamy** [comment]
Yeah, pp calculation changes always mess with sse, it's the same as the last time they changed pp calculation.
But that's a drawback I'll have to accept when trying to be efficient and only update lazily.

However something like 'update all' and 'force update all' was something I also felt would be useful sometimes.
I think I will add those buttons to the options menu so they don't clutter the user profile.

They are currently changing everything the entire time, so testing isn't that easy, everything is at 0pp lul
So yeah, I'll prepare some changes and push them and then see along when everything calms down

**Comment by Splamy** [comment]
Alright, I added '(Force) update all users' buttons. You can check them out whether they work without problems
