### ISSUE TITLE
Issue that when add user to cache

### ISSUE THREAD

**Issue by 354316936** [Splamy/ScoreSaberEnhanced#21]
![image](https://user-images.githubusercontent.com/34342424/93174536-20c20880-f6fc-11ea-9698-25e55260ab9f.png)
![image](https://user-images.githubusercontent.com/34342424/93174642-523ad400-f6fc-11ea-977e-46bae1c00594.png)

Adding some users to the cache sometimes fails, the number of empty pages cannot be read.

**Comment by Lemmmy** [comment]
I'm experiencing this issue too, I suspect its when the final page has the maximum number of scores in pagination (i.e. 8 scores), so there's no new page to get. The responsible code is likely here:

https://github.com/Splamy/ScoreSaberEnhanced/blob/52c5a05a9d02d329eb8ae214b3f5ec7f500fc921/src/api/scoresaber.ts#L29

I think an additional check should be added when fetching a score page for a 404 status code, stopping pagination and assuming it's the end of the results.

**Comment by Lemmmy** [comment]
I created a PR to fix this: #23
